reviewers:
  defaults:
    - kkojae91
    - moonheekim0118
    - hyewoncc
    - JangBomi
    - yeon-06
    - HJ-Rich
  groups:
    backend:
      - hyewoncc
      - JangBomi
      - yeon-06
      - HJ-Rich
    frontend:
      - kkojae91
      - moonheekim0118

files:
  "frontend/**":
    - frontend
  "backend/**":
    - backend

options:
  ignore_draft: true

  enable_group_assignment: false

  number_of_reviewers: 3
